version: '3.8'
services:
  mysql:
    image: mysql:8.0.30
    platform: linux/arm64/v8
    command: "mysqld --character-set-server=utf8mb4"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: homework
      MYSQL_USER: homework
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
